---
title: C6312 | Microsoft Docs
ms.date: 11/15/2016
ms.prod: visual-studio-dev14
ms.technology: vs-ide-code-analysis
ms.topic: reference
f1_keywords:
- C6312
helpviewer_keywords:
- C6312
ms.assetid: 1fc8b9a1-e6ba-4799-84c3-31f289576cca
caps.latest.revision: 15
author: corob-msft
ms.author: corob
manager: jillfra
ms.openlocfilehash: 2f33d2a6e7e87f14859614fa25e1bd846764b944
ms.sourcegitcommit: 68f893f6e472df46f323db34a13a7034dccad25a
ms.translationtype: MT
ms.contentlocale: cs-CZ
ms.lasthandoff: 02/15/2020
ms.locfileid: "77273913"
---
# <a name="c6312"></a>C6312
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

Upozornění C6312: možnou nekonečnou smyčku: použití konstanty EXCEPTION_CONTINUE_EXECUTION ve výrazu filtru výjimky try-except  
  
 Toto upozornění označuje použití konstanty `EXCEPTION_CONTINUE_EXECUTION` (nebo jiné konstanty, která je vyhodnocena na hodnotu-1) ve výrazu filtru strukturované obslužné rutiny výjimky. Použití konstantní hodnoty `EXCEPTION_CONTINUE_EXECUTION` může vést k nekonečné smyčce. Například pokud byla výjimka vyvolána hardwarem, bude instrukce, která způsobila výjimku, restartována. Pokud je adresa, která způsobila výjimku, stále chybná, dojde k další výjimce, která bude zpracována stejným způsobem. To způsobuje nekonečnou smyčku.  
  
 Explicitní volání `RaiseException` nebude přímo způsobovat nekonečnou smyčku, ale bude pokračovat v provádění kódu v chráněném bloku. To může být neočekávané a může vést k nekonečné smyčce, pokud se `RaiseException` použila k tomu, aby se zabránilo přesměrování neplatného ukazatele.  
  
 `EXCEPTION_CONTINUE_EXECUTION` by měl být obvykle vrácen pouze funkcí volanou ve výrazu filtru, který má možnost opravit buď ukazatel, který způsobil výjimku, nebo základní paměť.  
  
## <a name="example"></a>Příklad  
 Následující kód vygeneruje toto upozornění:  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *ptr)  
{  
  __try   
  {  
    // exception occurs if the caller passes null ptr  
    // code...     
   *ptr = '\0';  
  }   
  __except (EXCEPTION_CONTINUE_EXECUTION)  
    // When EXCEPTION_CONTINUE_EXECUTION is used, the handler  
    //  block of the structured exception handler is not executed.   
  {  
    puts("This block is never executed");  
  }  
}  
```  
  
 Chcete-li toto upozornění opravit, použijte následující kód:  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *ptr)  
{  
  __try   
  {  
    // exception occurs if the caller passes null ptr  
    // code...  
    *ptr = '\0';  
  }   
  __except (GetExceptionCode()== EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)   
  {  
    puts("Error Occurred");  
  }  
}  
```
