---
title: C28105 | Microsoft Docs
ms.custom: 
ms.date: 11/04/2016
ms.reviewer: 
ms.suite: 
ms.technology: vs-ide-code-analysis
ms.tgt_pltfrm: 
ms.topic: article
f1_keywords: C28105
helpviewer_keywords: C28105
ms.assetid: 5afdec78-30eb-470c-980f-93d0cb3e74cc
caps.latest.revision: "3"
author: mikeblome
ms.author: mblome
manager: ghogen
ms.workload: multiple
ms.openlocfilehash: 21b1f4923621105f84ea8dca78fb31006fffde49
ms.sourcegitcommit: 32f1a690fc445f9586d53698fc82c7debd784eeb
ms.translationtype: MT
ms.contentlocale: cs-CZ
ms.lasthandoff: 12/22/2017
---
# <a name="c28105"></a>C28105
Upozornění C28105: Úniku prostředků kvůli výjimce  
  
 Zadaný prostředek není uvolněno, když dojde k výjimce. Příkaz určený argumentem cesta může vyvolat výjimku. Toto upozornění je podobná upozornění [C28103](../code-quality/c28103.md)kromě toho, že v tomto případě je zahrnuta výjimku.  
  
## <a name="example"></a>Příklad  
 Následující příklad kódu generuje toto upozornění:  
  
```  
res = KeSaveFloatingPointState(buffer);  
  
res = AllocateResource(Resource);  
char *p2 = new char[10]; // could throw  
  
delete[] p2;  
FreeResource(Resource)  
```  
  
 Následující příklad kódu zabraňuje toto upozornění:  
  
```  
res = AllocateResource(Resource);  
char *p2;  
  
try {  
    p2 = new char[10];  
} catch (std::bad_alloc *e) {  
    // just handle the throw  
    ;  
}  
FreeResource(Resource)  
```